name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/snekussaurier/whatsapp-chat-statistics:latest -t ghcr.io/snekussaurier/whatsapp-chat-statistics:${{ github.sha }} .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/snekussaurier/whatsapp-chat-statistics:latest && docker push ghcr.io/snekussaurier/whatsapp-chat-statistics:${{ github.sha }}

      - name: Logout from GHCR
        run: docker logout ghcr.io
